const supabaseURL = 'https://appibxbabgskurddmnjz.supabase.co'
const supabaseKey = "process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcGlieGJhYmdza3VyZGRtbmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTIxNTAxMzUsImV4cCI6MjAyNzcyNjEzNX0.8xzTcqjZv98GOVy0GkzDPl4HK5d1UVAo8vNLEwRU-xw"
export const supabase = createClient(supabaseURL, supabaseKey)